title: SemiTO-V Team PoliTO
description: A RISC-V student team at Polytechnic University of Turin specialized in processor design and low level software/firmware development
theme: just-the-docs

url: https://just-the-docs.github.io

logo: "/assets/semitofivelogo.png"

favicon_ico: "/assets/favicon.ico"

color_scheme: semito

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
